language: node_js
node_js:
  - "8"
cache:
  directories:
      - "node_modules"
install: npm install --production
script: npm run export
before_deploy: npm install now --no-save
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
